import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  modal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0 , 0.5)',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    alignSelf: 'center',
    margin: 'auto',
  },
  header: {
    fontWeight: 'bold',
    fontSize: 25,
    marginBottom: 10,
    marginTop: 20,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 0.5,
  },
  paused: {
    fontWeight: 'bold',
    alignSelf: 'center',
    fontSize: 25,
    marginBottom: 5,
    marginTop: 0,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 0.5,
    top: 0,
  },
  score: {
    fontWeight: 'bold',
    color: 'red',
    fontSize: 23,
    marginBottom: 5,
    marginTop: 5,
    textShadowColor: 'black',
    textShadowOffset: {width: 0, height: 3},
    textShadowRadius: 2,
  },
  timeScore: {
    flexDirection: 'row',
    fontWeight: 'bold',
    color: 'red',
    fontSize: 30,
    marginBottom: 5,
    marginTop: 5,
    textShadowColor: 'black',
    textShadowOffset: {width: 0, height: 3},
    textShadowRadius: 2,
  },
  overlay: {
    backgroundColor: 'rgba(0, 0, 0 , 0.5)',
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  continueButtonBox: {
    width: 200,
    height: 150,
    backgroundColor: 'white',
    justifyContent: 'center',
    margin: 'auto',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.3,
    shadowRadius: 1,
    top: -100,
  },
  continueButton: {
    height: 35,
    minWidth: 70,
    borderRadius: 10,
    margin: 5,
    padding: 5,
    top: 40,
  },
  buttonBox: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    position: 'absolute',
    top: 30,
    left: 220,
  },
  button: {
    borderRadius: 10,
    height: 35,
    minWidth: 70,
    margin: 5,
    padding: 5,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  hole: {
    flex: 1,
    width: 80,
    height: 80,
    margin: 10,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    shadowRadius: 3,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 1},
  },
  mole: {
    flex: 1,
    width: 80,
    height: 80,
    margin: 10,
    shadowRadius: 3,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 1},
  },
});
export default styles;
